name = "d1-tutorial"
main = "src/index.ts"
compatibility_date = "2023-09-18"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "weurDatabase"
database_id = "564b2f92-ee17-4394-9896-d7fc4d528c4a"